### ISSUE TITLE
There is a error: [unhashable type: 'numpy.ndarray'] when convet weights

### ISSUE THREAD

**Issue by corn27** [chi0tzp/PyVGGFace#3]
Hi, thank you for your work. I meet some mistakes when convert weights:

Traceback (most recent call last):
  File "E:/BaoXiu/EX8/PyVGGFace-master/convert_weights.py", line 67, in <module>
    model=vggface_model)
  File "E:/BaoXiu/EX8/PyVGGFace-master/convert_weights.py", line 32, in convert
    torch_model = torchfile.load(torch_weights_file)
  File "C:\ProgramData\Anaconda3\envs\temp\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "C:\ProgramData\Anaconda3\envs\temp\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\ProgramData\Anaconda3\envs\temp\lib\site-packages\torchfile.py", line 387, in read_obj
    obj[k] = v
TypeError: unhashable type: 'numpy.ndarray'

And my envs is:

numpy (1.14.3)
Pillow (5.2.0)
pip (9.0.1)
torch (1.1.0)
torchfile (0.1.0)
torchvision (0.3.0)

Could you give me some help?

**Comment by corn27** [comment]
I have solved the program, thank you.

**Comment by INERTIA2001** [comment]
I have the same error, how do you solve the problem?

**Comment by goldiusleonard** [comment]
Me too. Any solutions for it?
